apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syspass-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syspass-backup-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: syspass
  name: syspass-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syspass
  template:
    metadata:
      labels:
        app: syspass
    spec:
      containers:
      - image: nuxsmin/docker-syspass
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/var/www/html/sysPass/config"
          name: syspass-config-pvc
        - mountPath: "/var/www/html/sysPass/backup"
          name: syspass-backup-pvc
      volumes:
      - name: syspass-config-pvc
        persistentVolumeClaim:
          claimName: syspass-config-pvc
      - name: syspass-backup-pvc
        persistentVolumeClaim:
          claimName: syspass-backup-pvc