apiVersion: v1
kind: Service
metadata:
  labels:
    app: syspass
  name: syspass-service
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: syspass
  type: LoadBalancer